config/routes.rb
Rails.application.routes.draw do
  devise_for :organizations
  # root to: "home#index"
  get "organization_root" => "organizations#show"
  devise_scope :organization do
    root to: 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :organizations do
    resources :nodes, only: [ :show, :new, :create, :edit, :update ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ApplicationRecord
  has_ancestry
  validates :name, uniqueness: true, presence: true
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true, presence: true
  has_many :nodes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_organization!, only: :index
  def index
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
before_action :find_node, only: [:show, :edit, :update, :destroy]

  def index
    @nodes = Node.all
  end

  def show
  end

  def new
    # @organization = Organization.find(params[:parent_id])
    @node = Node.new
  end

  def create
    @node = Node.new(node_params)
    # @organization = Organization.find(params[:parent_id])
    @node.organization = @organization
    if @node.save
      redirect_to organization_path(@organization)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @node.update(node_params)
      redirect_to organization_node_path(@node)
    else
      render :edit
    end
  end

  private

  def find_node
    @node = Node.find(params[:id])
  end

  def node_params
    params.require(:node).permit(:name)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :find_organization, only: [:show]

  def show
    @nodes = Node.where(ancestry: params[:id])
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organization_path(@organization)
    else
      render :new
    end
  end

  private

  def find_organization
    @organization = Organization.find(current_organization.id)
  end

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudioApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node, url: new_organization_node_path, method: :get) do |f| %>
  <%= f.hidden_field :parent_id %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/nodes/new.html.erb
<%= render "form", node: @node %>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/organizations/new.html.erb
<%= render "form", organization: @organization %>

app/views/organizations/show.html.erb
<h1>Your organization: <%= @organization.name %></h1>
<h2>Nodes:</h2>
<ul>
  <% @nodes.each do |node| %>
    <li><%= node.name %></li>
  <% end %>
</ul>

<%= link_to 'create node', new_organization_node_path(@organization) %>